environment: dev

image:
  repository: roboshopdevacr.azurecr.io/cart
  tag: "main-846171d"

replicaCount: 1

service:
  port: 80
  targetPort: 8080

appCommand: "node /app/server.js"
healthPath: "/health"

ingress:
  enabled: false

vault:
  enabled: true
  role: roboshop-dev
  secrets:
    - name: mongodb
      path: secret/data/roboshop/dev/mongodb
      envVars:
        - envName: MONGO_URL
          secretKey: uri
    - name: redis
      path: secret/data/roboshop/dev/redis
      envVars:
        - envName: REDIS_HOST
          secretKey: host
        - envName: REDIS_PORT
          secretKey: port
        - envName: REDIS_PASSWORD
          secretKey: password

env:
  APP_ENV: dev
  CATALOGUE_HOST: catalogue-svc
  CATALOGUE_PORT: "80"