serviceName: catalogue
# Catalogue service — dev environment
environment: dev

image:
  repository: roboshopdevacr.azurecr.io/catalogue
  tag: "main-a6f07f9"

replicaCount: 1

service:
  port: 80
  targetPort: 8080

appCommand: "node /app/server.js"
healthPath: "/health"

ingress:
  enabled: false   # catalogue is internal — no public ingress
  # frontend calls catalogue via service name

vault:
  enabled: true
  role: roboshop-dev
  secrets:
    - name: mongodb
      path: secret/data/roboshop/dev/mongodb
      envVars:
        - envName: MONGO_URL
          secretKey: uri

env:
  APP_ENV: dev
  LOG_LEVEL: debug

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 256Mi

hpa:
  enabled: false   # enable later when load testing